#
#    mvpartition - A disk partitions/RAID/LVM setup tool
#    Copyright (C) 2010-2015  MontaVista Software, LLC
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor,
#      Boston, MA  02110-1301  USA

#
# Map curses keys to string.
# Why isn't this part of python curses?
#

import curses

keymap = {
    curses.KEY_A1: 'A1',
    curses.KEY_A3: 'A3',
    curses.KEY_B2: 'B2',
    curses.KEY_BACKSPACE: 'BACKSPACE',
    curses.KEY_BEG: 'BEG',
    curses.KEY_BTAB: 'BTAB',
    curses.KEY_C1: 'C1',
    curses.KEY_C3: 'C3',
    curses.KEY_CANCEL: 'CANCEL',
    curses.KEY_CATAB: 'CATAB',
    curses.KEY_CLEAR: 'CLEAR',
    curses.KEY_CLOSE: 'CLOSE',
    curses.KEY_COMMAND: 'COMMAND',
    curses.KEY_COPY: 'COPY',
    curses.KEY_CREATE: 'CREATE',
    curses.KEY_CTAB: 'CTAB',
    curses.KEY_DC: 'DC',
    curses.KEY_DL: 'DL',
    curses.KEY_DOWN: 'DOWN',
    curses.KEY_EIC: 'EIC',
    curses.KEY_END: 'END',
    curses.KEY_ENTER: 'ENTER',
    curses.KEY_EOL: 'EOL',
    curses.KEY_EOS: 'EOS',
    curses.KEY_EXIT: 'EXIT',
    curses.KEY_F0: 'F0',
    curses.KEY_F1: 'F1',
    curses.KEY_F10: 'F10',
    curses.KEY_F11: 'F11',
    curses.KEY_F12: 'F12',
    curses.KEY_F13: 'F13',
    curses.KEY_F14: 'F14',
    curses.KEY_F15: 'F15',
    curses.KEY_F16: 'F16',
    curses.KEY_F17: 'F17',
    curses.KEY_F18: 'F18',
    curses.KEY_F19: 'F19',
    curses.KEY_F2: 'F2',
    curses.KEY_F20: 'F20',
    curses.KEY_F21: 'F21',
    curses.KEY_F22: 'F22',
    curses.KEY_F23: 'F23',
    curses.KEY_F24: 'F24',
    curses.KEY_F25: 'F25',
    curses.KEY_F26: 'F26',
    curses.KEY_F27: 'F27',
    curses.KEY_F28: 'F28',
    curses.KEY_F29: 'F29',
    curses.KEY_F3: 'F3',
    curses.KEY_F30: 'F30',
    curses.KEY_F31: 'F31',
    curses.KEY_F32: 'F32',
    curses.KEY_F33: 'F33',
    curses.KEY_F34: 'F34',
    curses.KEY_F35: 'F35',
    curses.KEY_F36: 'F36',
    curses.KEY_F37: 'F37',
    curses.KEY_F38: 'F38',
    curses.KEY_F39: 'F39',
    curses.KEY_F4: 'F4',
    curses.KEY_F40: 'F40',
    curses.KEY_F41: 'F41',
    curses.KEY_F42: 'F42',
    curses.KEY_F43: 'F43',
    curses.KEY_F44: 'F44',
    curses.KEY_F45: 'F45',
    curses.KEY_F46: 'F46',
    curses.KEY_F47: 'F47',
    curses.KEY_F48: 'F48',
    curses.KEY_F49: 'F49',
    curses.KEY_F5: 'F5',
    curses.KEY_F50: 'F50',
    curses.KEY_F51: 'F51',
    curses.KEY_F52: 'F52',
    curses.KEY_F53: 'F53',
    curses.KEY_F54: 'F54',
    curses.KEY_F55: 'F55',
    curses.KEY_F56: 'F56',
    curses.KEY_F57: 'F57',
    curses.KEY_F58: 'F58',
    curses.KEY_F59: 'F59',
    curses.KEY_F6: 'F6',
    curses.KEY_F60: 'F60',
    curses.KEY_F61: 'F61',
    curses.KEY_F62: 'F62',
    curses.KEY_F63: 'F63',
    curses.KEY_F7: 'F7',
    curses.KEY_F8: 'F8',
    curses.KEY_F9: 'F9',
    curses.KEY_FIND: 'FIND',
    curses.KEY_HELP: 'HELP',
    curses.KEY_HOME: 'HOME',
    curses.KEY_IC: 'IC',
    curses.KEY_IL: 'IL',
    curses.KEY_LEFT: 'LEFT',
    curses.KEY_LL: 'LL',
    curses.KEY_MARK: 'MARK',
    curses.KEY_MESSAGE: 'MESSAGE',
    curses.KEY_MOVE: 'MOVE',
    curses.KEY_NEXT: 'NEXT',
    curses.KEY_NPAGE: 'NPAGE',
    curses.KEY_OPEN: 'OPEN',
    curses.KEY_OPTIONS: 'OPTIONS',
    curses.KEY_PPAGE: 'PPAGE',
    curses.KEY_PREVIOUS: 'PREVIOUS',
    curses.KEY_PRINT: 'PRINT',
    curses.KEY_REDO: 'REDO',
    curses.KEY_REFERENCE: 'REFERENCE',
    curses.KEY_REFRESH: 'REFRESH',
    curses.KEY_REPLACE: 'REPLACE',
    curses.KEY_RESTART: 'RESTART',
    curses.KEY_RESUME: 'RESUME',
    curses.KEY_RIGHT: 'RIGHT',
    curses.KEY_SAVE: 'SAVE',
    curses.KEY_SBEG: 'SBEG',
    curses.KEY_SCANCEL: 'SCANCEL',
    curses.KEY_SCOMMAND: 'SCOMMAND',
    curses.KEY_SCOPY: 'SCOPY',
    curses.KEY_SCREATE: 'SCREATE',
    curses.KEY_SDC: 'SDC',
    curses.KEY_SDL: 'SDL',
    curses.KEY_SELECT: 'SELECT',
    curses.KEY_SEND: 'SEND',
    curses.KEY_SEOL: 'SEOL',
    curses.KEY_SEXIT: 'SEXIT',
    curses.KEY_SF: 'SF',
    curses.KEY_SFIND: 'SFIND',
    curses.KEY_SHELP: 'SHELP',
    curses.KEY_SHOME: 'SHOME',
    curses.KEY_SIC: 'SIC',
    curses.KEY_SLEFT: 'SLEFT',
    curses.KEY_SMESSAGE: 'SMESSAGE',
    curses.KEY_SMOVE: 'SMOVE',
    curses.KEY_SNEXT: 'SNEXT',
    curses.KEY_SOPTIONS: 'SOPTIONS',
    curses.KEY_SPREVIOUS: 'SPREVIOUS',
    curses.KEY_SPRINT: 'SPRINT',
    curses.KEY_SR: 'SR',
    curses.KEY_SREDO: 'SREDO',
    curses.KEY_SREPLACE: 'SREPLACE',
    curses.KEY_SRIGHT: 'SRIGHT',
    curses.KEY_SRSUME: 'SRSUME',
    curses.KEY_SSAVE: 'SSAVE',
    curses.KEY_SSUSPEND: 'SSUSPEND',
    curses.KEY_STAB: 'STAB',
    curses.KEY_SUNDO: 'SUNDO',
    curses.KEY_SUSPEND: 'SUSPEND',
    curses.KEY_UNDO: 'UNDO',
    curses.KEY_UP: 'UP',
    0x00: '^@',
    0x01: '^A',
    0x02: '^B',
    0x03: '^C',
    0x04: '^D',
    0x05: '^E',
    0x06: '^F',
    0x07: '^G',
    0x08: '^H',
    0x09: 'TAB',
    0x0a: 'ENTER',
    0x0b: '^K',
    0x0c: '^L',
    0x0d: '^M',
    0x0e: '^N',
    0x0f: '^O',
    0x10: '^P',
    0x11: '^Q',
    0x12: '^R',
    0x13: '^S',
    0x14: '^T',
    0x15: '^U',
    0x16: '^V',
    0x17: '^W',
    0x18: '^X',
    0x19: '^Y',
    0x1a: '^Z',
    0x1b: 'ESC',
    0x1c: '^\\',
    0x1d: '^]',
    0x1e: '^^',
    0x1f: '^_',
    0x7f: 'DEL'
    }

def keyToStr(c):
    if c in keymap:
        return keymap[c]

    if (c >= 32 and c <= 126):
        return chr(c)

    return "Int(%d)" % c
